package live.talkshop.sdk.resources

internal object Keys {
    const val KEY_KEY = "key"
    const val KEY_ID = "id"
    const val KEY_TITLE = "title"
    const val KEY_URL = "url"
    const val KEY_DATA = "data"
    const val KEY_DESCRIPTION = "description"
    const val KEY_STATE = "state"
    const val KEY_ASSETS = "assets"
    const val KEY_CHANNEL_ID = "channel_id"
    const val KEY_TRANSCRIPTION_URL = "transcription_url"
    const val KEY_CHANNEL = "channel"
    const val KEY_SCHEDULED_LIVE_AT = "scheduled_live_at"
    const val KEY_ENDED_AT = "ended_at"
    const val KEY_DURATION = "duration"
    const val KEY_THUMBNAIL_IMAGE_URL = "thumbnail_image_url"
    const val KEY_THUMBNAIL_IMAGE = "thumbnail_image"
    const val KEY_NAME = "name"
    const val KEY_PRODUCT_IDS = "show_product_ids"
    const val KEY_SHOW_PRODUCTS = "show_products"
    const val KEY_PUBLISH_KEY = "publish_key"
    const val KEY_SUBSCRIBE_KEY = "subscribe_key"
    const val KEY_TOKEN = "token"
    const val KEY_USER_ID = "user_id"
    const val KEY_VALID_KEY = "valid_key"
    const val KEY_CREATED_AT = "createdAt"
    const val KEY_SENDER = "sender"
    const val KEY_TEXT = "text"
    const val KEY_TYPE = "type"
    const val KEY_PLATFORM = "platform"
    const val KEY_ASPECT_RATIO = "aspectRatio"
    const val KEY_TIME_TOKEN = "timetoken"
    const val KEY_TIME_ORIGINAL = "original"
    const val KEY_TIME_MESSAGE = "message"
    const val KEY_PROFILE_URL = "profileUrl"
    const val KEY_FILE_EXTENSION = "file_extension"
    const val KEY_CHANNEL_CODE = "channelCode"
    const val KEY_IS_VERIFIED = "isVerified"
    const val KEY_TRAILER = "trailer"
    const val KEY_KIND = "kind"
    const val KEY_ENTRANCE = "entrance"
    const val KEY_PRODUCT_ID = "product_id"
}